version: "3.7"
services:
  app:
    build:
      args:
        user: Tom
        uid: 197609
      context: ./
      dockerfile: Dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teallen

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - teallen

networks:
  teallen:
    name: teallen
    driver: bridge
